from django.urls import path, include
from rest_framework.routers import DefaultRouter

from comment import views

# the default router automatically generates the urls for our viewset
# when we have a viewset we may have multiple
# urls associated with that 1 viewset.
# e.g.
# /api/gallery/tags
# /api/gallery/tags/1
# /api/gallery/tags/5/edit
# it automatically registers the appropriate urls for all the
# actions in our viewset
router = DefaultRouter()
router.register('comments', views.CommentViewSet)


app_name = 'comment'

# all the urls that are generated by our default router
# will be included in our urlpatterns
urlpatterns = [
    path('', include(router.urls))
]
