# Generated by Django 2.1.8 on 2019-05-07 15:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190507_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.image_file_path),
        ),
    ]
