from django.urls import path, include
from rest_framework.routers import DefaultRouter

from recipe import views

# the default router automatically generates the urls for our viewset
# when we have a viewset we may have multiple
# urls associated with that 1 viewset.
# e.g.
# /api/recipe/tags
# /api/recipe/tags/1
# /api/recipe/tags/5/edit
# it automatically registers the appropriate urls for all the
# actions in our viewset
router = DefaultRouter()
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)
router.register('recipes', views.RecipeViewSet)

app_name = 'recipe'

# all the urls that are generated by our default router
# will be included in our urlpatterns
urlpatterns = [
    path('', include(router.urls))
]
